[package]
name = "yenc"
version = "0.0.0"
edition = "2024"
description = "SIMD accelerated implementation of yEnc format"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
